version: '3'
services:

  redis:
    image: redis:latest
    container_name: redis
    #command: redis-server --requirepass mypassword
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  redis-insights:
    container_name: redis-insights
    image: redislabs/redisinsight
    ports: 
      - "8082:8001"

  rediscluster:
    image: grokzen/redis-cluster:latest
    container_name: rediscluster
    restart: unless-stopped
    ports:
      - "7000-7005:7000-7005"
    environment:
      IP: 0.0.0.0
